import '../styles/globals.css';
import { Providers } from './Providers';

import GlobalSidebar from '@/components/GlobalSidebar';
import SidebarToggle from '@/components/SidebarToggle';
// Note: do not call useUIState directly in this server component — use GlobalSidebar (client) to read state.

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          {children}
          <SidebarToggle />
          <GlobalSidebar />
        </Providers>
      </body>
    </html>
  );
}
