/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * post.proto
 * OpenAPI spec version: version not set
 */

export * from './postServiceGetPostsParams';
export * from './protobufAny';
export * from './rpcStatus';
export * from './v1CreatePostRequest';
export * from './v1EditPostRequest';
export * from './v1GetPostsByUserIDResponse';
export * from './v1GetPostsRequest';
export * from './v1GetPostsResponse';
export * from './v1Post';
export * from './v1StandardResponse';