/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * post.proto
 * OpenAPI spec version: version not set
 */

export interface V1CreatePostRequest {
  content?: string;
  image?: string;
  lat?: number;
  lng?: number;
}
