/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * post.proto
 * OpenAPI spec version: version not set
 */
import type { V1Post } from './v1Post';

export interface V1GetPostsByUserIDResponse {
  posts?: V1Post[];
}
