/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * post.proto
 * OpenAPI spec version: version not set
 */

export interface V1StandardResponse {
  success?: boolean;
  message?: string;
}
