root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "api/pd"]
  kill_delay = "2s"
  send_interrupt = true
  poll = true
  poll_interval = 1000

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true