linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: CHAP_Grpc/backend
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck
    - gosimple
    - structcheck
    - varcheck
    - deadcode
  disable:
    - errcheck  # gRPCコードでは一時的に無効化

run:
  timeout: 5m
  go: "1.21"

issues:
  exclude-rules:
    # テストファイルでは一部のlintを無効化
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  # 生成されたprotobufファイルを除外
  exclude-dirs:
    - api/pd

output:
  format: colored-line-number