//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::auth_db_models::Entity as AuthDbModels;
pub use super::comment_db_models::Entity as CommentDbModels;
pub use super::event_db_models::Entity as EventDbModels;
pub use super::event_like_db_models::Entity as EventLikeDbModels;
pub use super::events::Entity as Events;
pub use super::post_db_models::Entity as PostDbModels;
pub use super::post_like_db_models::Entity as PostLikeDbModels;
pub use super::posts::Entity as Posts;
pub use super::spot_db_models::Entity as SpotDbModels;
pub use super::thread_db_models::Entity as ThreadDbModels;
pub use super::thread_like_db_models::Entity as ThreadLikeDbModels;
pub use super::threads::Entity as Threads;
pub use super::user_db_models::Entity as UserDbModels;
