//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "spot_db_models")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    #[sea_orm(column_type = "Decimal(Some((10, 8)))")]
    pub lat: Decimal,
    #[sea_orm(column_type = "Decimal(Some((11, 8)))")]
    pub lng: Decimal,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub valid: Option<bool>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_db_models::Entity",
        from = "Column::UserId",
        to = "super::user_db_models::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserDbModels,
}

impl Related<super::user_db_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDbModels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
