/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * user.proto
 * OpenAPI spec version: version not set
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  RpcStatus,
  UserServiceFollowUserBody,
  V1EditUserRequest,
  V1GetUserByIDResponse,
  V1StandardResponse
} from './';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const userServiceDeleteUser = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<V1StandardResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/users/delete/${userId}`,options
    );
  }



export const getUserServiceDeleteUserMutationOptions = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceDeleteUser>>, TError,{userId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userServiceDeleteUser>>, TError,{userId: string}, TContext> => {

const mutationKey = ['userServiceDeleteUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userServiceDeleteUser>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  userServiceDeleteUser(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserServiceDeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof userServiceDeleteUser>>>
    
    export type UserServiceDeleteUserMutationError = AxiosError<RpcStatus>

    export const useUserServiceDeleteUser = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceDeleteUser>>, TError,{userId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userServiceDeleteUser>>,
        TError,
        {userId: string},
        TContext
      > => {

      const mutationOptions = getUserServiceDeleteUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const userServiceEditUser = (
    v1EditUserRequest: V1EditUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<V1StandardResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/users/edit`,
      v1EditUserRequest,options
    );
  }



export const getUserServiceEditUserMutationOptions = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceEditUser>>, TError,{data: V1EditUserRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userServiceEditUser>>, TError,{data: V1EditUserRequest}, TContext> => {

const mutationKey = ['userServiceEditUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userServiceEditUser>>, {data: V1EditUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  userServiceEditUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserServiceEditUserMutationResult = NonNullable<Awaited<ReturnType<typeof userServiceEditUser>>>
    export type UserServiceEditUserMutationBody = V1EditUserRequest
    export type UserServiceEditUserMutationError = AxiosError<RpcStatus>

    export const useUserServiceEditUser = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceEditUser>>, TError,{data: V1EditUserRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userServiceEditUser>>,
        TError,
        {data: V1EditUserRequest},
        TContext
      > => {

      const mutationOptions = getUserServiceEditUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary ユーザー操作
 */
export const userServiceGetMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<V1GetUserByIDResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/users/me`,options
    );
  }


export const getUserServiceGetMeQueryKey = () => {
    return [`/api/v1/users/me`] as const;
    }

    
export const getUserServiceGetMeQueryOptions = <TData = Awaited<ReturnType<typeof userServiceGetMe>>, TError = AxiosError<RpcStatus>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserServiceGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userServiceGetMe>>> = ({ signal }) => userServiceGetMe({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserServiceGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof userServiceGetMe>>>
export type UserServiceGetMeQueryError = AxiosError<RpcStatus>


export function useUserServiceGetMe<TData = Awaited<ReturnType<typeof userServiceGetMe>>, TError = AxiosError<RpcStatus>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userServiceGetMe>>,
          TError,
          Awaited<ReturnType<typeof userServiceGetMe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserServiceGetMe<TData = Awaited<ReturnType<typeof userServiceGetMe>>, TError = AxiosError<RpcStatus>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userServiceGetMe>>,
          TError,
          Awaited<ReturnType<typeof userServiceGetMe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserServiceGetMe<TData = Awaited<ReturnType<typeof userServiceGetMe>>, TError = AxiosError<RpcStatus>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ユーザー操作
 */

export function useUserServiceGetMe<TData = Awaited<ReturnType<typeof userServiceGetMe>>, TError = AxiosError<RpcStatus>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userServiceGetMe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserServiceGetMeQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const userServiceUnfollowUser = (
    targetUserId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<V1StandardResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/users/${targetUserId}/follow`,options
    );
  }



export const getUserServiceUnfollowUserMutationOptions = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceUnfollowUser>>, TError,{targetUserId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userServiceUnfollowUser>>, TError,{targetUserId: string}, TContext> => {

const mutationKey = ['userServiceUnfollowUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userServiceUnfollowUser>>, {targetUserId: string}> = (props) => {
          const {targetUserId} = props ?? {};

          return  userServiceUnfollowUser(targetUserId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserServiceUnfollowUserMutationResult = NonNullable<Awaited<ReturnType<typeof userServiceUnfollowUser>>>
    
    export type UserServiceUnfollowUserMutationError = AxiosError<RpcStatus>

    export const useUserServiceUnfollowUser = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceUnfollowUser>>, TError,{targetUserId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userServiceUnfollowUser>>,
        TError,
        {targetUserId: string},
        TContext
      > => {

      const mutationOptions = getUserServiceUnfollowUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const userServiceFollowUser = (
    targetUserId: string,
    userServiceFollowUserBody: UserServiceFollowUserBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<V1StandardResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/users/${targetUserId}/follow`,
      userServiceFollowUserBody,options
    );
  }



export const getUserServiceFollowUserMutationOptions = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceFollowUser>>, TError,{targetUserId: string;data: UserServiceFollowUserBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userServiceFollowUser>>, TError,{targetUserId: string;data: UserServiceFollowUserBody}, TContext> => {

const mutationKey = ['userServiceFollowUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userServiceFollowUser>>, {targetUserId: string;data: UserServiceFollowUserBody}> = (props) => {
          const {targetUserId,data} = props ?? {};

          return  userServiceFollowUser(targetUserId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserServiceFollowUserMutationResult = NonNullable<Awaited<ReturnType<typeof userServiceFollowUser>>>
    export type UserServiceFollowUserMutationBody = UserServiceFollowUserBody
    export type UserServiceFollowUserMutationError = AxiosError<RpcStatus>

    export const useUserServiceFollowUser = <TError = AxiosError<RpcStatus>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userServiceFollowUser>>, TError,{targetUserId: string;data: UserServiceFollowUserBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userServiceFollowUser>>,
        TError,
        {targetUserId: string;data: UserServiceFollowUserBody},
        TContext
      > => {

      const mutationOptions = getUserServiceFollowUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
