/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * comment.proto
 * OpenAPI spec version: version not set
 */

export * from './commentServiceGetCommentsByThreadIDParams';
export * from './protobufAny';
export * from './rpcStatus';
export * from './v1Comment';
export * from './v1CreateCommentRequest';
export * from './v1EditCommentRequest';
export * from './v1GetCommentsByThreadIDResponse';
export * from './v1StandardResponse';