/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * comment.proto
 * OpenAPI spec version: version not set
 */

export interface V1EditCommentRequest {
  commentId?: string;
  content?: string;
}
