/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * comment.proto
 * OpenAPI spec version: version not set
 */
import type { V1Comment } from './v1Comment';

export interface V1GetCommentsByThreadIDResponse {
  comments?: V1Comment[];
}
