/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * user.proto
 * OpenAPI spec version: version not set
 */

export * from './protobufAny';
export * from './rpcStatus';
export * from './userServiceFollowUserBody';
export * from './v1EditUserRequest';
export * from './v1GetUserByIDResponse';
export * from './v1StandardResponse';
export * from './v1User';