/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * user.proto
 * OpenAPI spec version: version not set
 */
import type { V1User } from './v1User';

export interface V1GetUserByIDResponse {
  user?: V1User;
}
