/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * user.proto
 * OpenAPI spec version: version not set
 */

export interface V1StandardResponse {
  success?: boolean;
  message?: string;
}
