/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * user.proto
 * OpenAPI spec version: version not set
 */

export interface V1User {
  id?: string;
  name?: string;
  description?: string;
  image?: string;
  createdAt?: string;
  updatedAt?: string;
  followerCount?: number;
  followingCount?: number;
  followers?: string[];
  followings?: string[];
}
