// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: spot.proto

package pd

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Spot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spot) Reset() {
	*x = Spot{}
	mi := &file_spot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spot) ProtoMessage() {}

func (x *Spot) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spot.ProtoReflect.Descriptor instead.
func (*Spot) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{0}
}

func (x *Spot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Spot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spot) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Spot) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Spot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Spot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSpotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spots         []*Spot                `protobuf:"bytes,1,rep,name=spots,proto3" json:"spots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpotsResponse) Reset() {
	*x = GetSpotsResponse{}
	mi := &file_spot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpotsResponse) ProtoMessage() {}

func (x *GetSpotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpotsResponse.ProtoReflect.Descriptor instead.
func (*GetSpotsResponse) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpotsResponse) GetSpots() []*Spot {
	if x != nil {
		return x.Spots
	}
	return nil
}

type CreateSpotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpotRequest) Reset() {
	*x = CreateSpotRequest{}
	mi := &file_spot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpotRequest) ProtoMessage() {}

func (x *CreateSpotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpotRequest.ProtoReflect.Descriptor instead.
func (*CreateSpotRequest) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpotRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSpotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSpotRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateSpotRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CreateSpotRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type EditSpotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSpotRequest) Reset() {
	*x = EditSpotRequest{}
	mi := &file_spot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSpotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSpotRequest) ProtoMessage() {}

func (x *EditSpotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSpotRequest.ProtoReflect.Descriptor instead.
func (*EditSpotRequest) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{3}
}

func (x *EditSpotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditSpotRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditSpotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditSpotRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *EditSpotRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type DeleteSpotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotId        string                 `protobuf:"bytes,1,opt,name=spot_id,json=spotId,proto3" json:"spot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpotRequest) Reset() {
	*x = DeleteSpotRequest{}
	mi := &file_spot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpotRequest) ProtoMessage() {}

func (x *DeleteSpotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpotRequest) Descriptor() ([]byte, []int) {
	return file_spot_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSpotRequest) GetSpotId() string {
	if x != nil {
		return x.SpotId
	}
	return ""
}

var File_spot_proto protoreflect.FileDescriptor

const file_spot_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spot.proto\x12\fchap.spot.v1\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\xb0\x01\n" +
	"\x04Spot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"<\n" +
	"\x10GetSpotsResponse\x12(\n" +
	"\x05spots\x18\x01 \x03(\v2\x12.chap.spot.v1.SpotR\x05spots\"\x85\x01\n" +
	"\x11CreateSpotRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\"}\n" +
	"\x0fEditSpotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\",\n" +
	"\x11DeleteSpotRequest\x12\x17\n" +
	"\aspot_id\x18\x01 \x01(\tR\x06spotId2\xc1\x03\n" +
	"\vSpotService\x12[\n" +
	"\bGetSpots\x12\x15.chap.common.v1.Empty\x1a\x1e.chap.spot.v1.GetSpotsResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/spots\x12p\n" +
	"\n" +
	"CreateSpot\x12\x1f.chap.spot.v1.CreateSpotRequest\x1a .chap.common.v1.StandardResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/spots/create\x12j\n" +
	"\bEditSpot\x12\x1d.chap.spot.v1.EditSpotRequest\x1a .chap.common.v1.StandardResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/spots/edit\x12w\n" +
	"\n" +
	"DeleteSpot\x12\x1f.chap.spot.v1.DeleteSpotRequest\x1a .chap.common.v1.StandardResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/api/v1/spots/delete/{spot_id}B1Z/github.com/uzak0209/CHAP_Grpc/backend/api/pd;pdb\x06proto3"

var (
	file_spot_proto_rawDescOnce sync.Once
	file_spot_proto_rawDescData []byte
)

func file_spot_proto_rawDescGZIP() []byte {
	file_spot_proto_rawDescOnce.Do(func() {
		file_spot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_proto_rawDesc), len(file_spot_proto_rawDesc)))
	})
	return file_spot_proto_rawDescData
}

var file_spot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spot_proto_goTypes = []any{
	(*Spot)(nil),              // 0: chap.spot.v1.Spot
	(*GetSpotsResponse)(nil),  // 1: chap.spot.v1.GetSpotsResponse
	(*CreateSpotRequest)(nil), // 2: chap.spot.v1.CreateSpotRequest
	(*EditSpotRequest)(nil),   // 3: chap.spot.v1.EditSpotRequest
	(*DeleteSpotRequest)(nil), // 4: chap.spot.v1.DeleteSpotRequest
	(*Empty)(nil),             // 5: chap.common.v1.Empty
	(*StandardResponse)(nil),  // 6: chap.common.v1.StandardResponse
}
var file_spot_proto_depIdxs = []int32{
	0, // 0: chap.spot.v1.GetSpotsResponse.spots:type_name -> chap.spot.v1.Spot
	5, // 1: chap.spot.v1.SpotService.GetSpots:input_type -> chap.common.v1.Empty
	2, // 2: chap.spot.v1.SpotService.CreateSpot:input_type -> chap.spot.v1.CreateSpotRequest
	3, // 3: chap.spot.v1.SpotService.EditSpot:input_type -> chap.spot.v1.EditSpotRequest
	4, // 4: chap.spot.v1.SpotService.DeleteSpot:input_type -> chap.spot.v1.DeleteSpotRequest
	1, // 5: chap.spot.v1.SpotService.GetSpots:output_type -> chap.spot.v1.GetSpotsResponse
	6, // 6: chap.spot.v1.SpotService.CreateSpot:output_type -> chap.common.v1.StandardResponse
	6, // 7: chap.spot.v1.SpotService.EditSpot:output_type -> chap.common.v1.StandardResponse
	6, // 8: chap.spot.v1.SpotService.DeleteSpot:output_type -> chap.common.v1.StandardResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spot_proto_init() }
func file_spot_proto_init() {
	if File_spot_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_proto_rawDesc), len(file_spot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_proto_goTypes,
		DependencyIndexes: file_spot_proto_depIdxs,
		MessageInfos:      file_spot_proto_msgTypes,
	}.Build()
	File_spot_proto = out.File
	file_spot_proto_goTypes = nil
	file_spot_proto_depIdxs = nil
}
