/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * thread.proto
 * OpenAPI spec version: version not set
 */

export interface ProtobufAny {
  '@type'?: string;
  [key: string]: unknown;
}
