/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * thread.proto
 * OpenAPI spec version: version not set
 */

export type ThreadServiceGetThreadsParams = {
lat?: number;
lng?: number;
};
