/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * thread.proto
 * OpenAPI spec version: version not set
 */
import type { V1Thread } from './v1Thread';

export interface V1GetThreadsResponse {
  threads?: V1Thread[];
}
