/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * thread.proto
 * OpenAPI spec version: version not set
 */
import type { V1Thread } from './v1Thread';
import type { V1Comment } from './v1Comment';

export interface V1GetThreadByIDResponse {
  thread?: V1Thread;
  comment?: V1Comment[];
}
