/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * thread.proto
 * OpenAPI spec version: version not set
 */

export interface V1Thread {
  id?: string;
  userName?: string;
  userId?: string;
  userImage?: string;
  content?: string;
  image?: string;
  likeCount?: number;
  createdAt?: string;
  updatedAt?: string;
  lat?: number;
  lng?: number;
  likes?: string[];
  comments?: string[];
  contentType?: string;
}
