/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */

export * from './eventServiceGetEventsParams';
export * from './protobufAny';
export * from './rpcStatus';
export * from './v1Comment';
export * from './v1CreateEventRequest';
export * from './v1EditEventRequest';
export * from './v1Event';
export * from './v1GetEventByIDResponse';
export * from './v1GetEventsRequest';
export * from './v1GetEventsResponse';
export * from './v1StandardResponse';