/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */

export interface V1CreateEventRequest {
  content?: string;
  image?: string;
  lat?: number;
  lng?: number;
  eventDate?: string;
  contentType?: string;
}
