/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */

export interface V1EditEventRequest {
  eventId?: string;
  eventDate?: string;
  content?: string;
  image?: string;
}
