/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */

export interface V1Event {
  id?: string;
  userName?: string;
  userId?: string;
  userImage?: string;
  content?: string;
  image?: string;
  likeCount?: number;
  createdAt?: string;
  updatedAt?: string;
  lat?: number;
  lng?: number;
  likes?: string[];
  eventDate?: string;
  contentType?: string;
}
