/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */
import type { V1Event } from './v1Event';

export interface V1GetEventsResponse {
  events?: V1Event[];
}
