/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * event.proto
 * OpenAPI spec version: version not set
 */
import type { V1Event } from './v1Event';
import type { V1Comment } from './v1Comment';

export interface V1GetEventByIDResponse {
  event?: V1Event;
  comment?: V1Comment[];
}
