/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * auth.proto
 * OpenAPI spec version: version not set
 */

export interface V1AuthResponse {
  success?: boolean;
  message?: string;
  token?: string;
}
