/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * spot.proto
 * OpenAPI spec version: version not set
 */

export * from './protobufAny';
export * from './rpcStatus';
export * from './v1CreateSpotRequest';
export * from './v1EditSpotRequest';
export * from './v1Empty';
export * from './v1GetSpotsResponse';
export * from './v1Spot';
export * from './v1StandardResponse';