/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * spot.proto
 * OpenAPI spec version: version not set
 */

export interface V1CreateSpotRequest {
  title?: string;
  description?: string;
  image?: string;
  lat?: number;
  lng?: number;
}
