/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * spot.proto
 * OpenAPI spec version: version not set
 */

export interface V1EditSpotRequest {
  id?: string;
  title?: string;
  description?: string;
  lat?: number;
  lng?: number;
}
