/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * spot.proto
 * OpenAPI spec version: version not set
 */
import type { V1Spot } from './v1Spot';

export interface V1GetSpotsResponse {
  spots?: V1Spot[];
}
