/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * spot.proto
 * OpenAPI spec version: version not set
 */

export interface V1Spot {
  id?: string;
  title?: string;
  description?: string;
  lat?: number;
  lng?: number;
  createdAt?: string;
  updatedAt?: string;
}
