/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * image.proto
 * OpenAPI spec version: version not set
 */

export * from './protobufAny';
export * from './rpcStatus';
export * from './v1UploadImageRequest';
export * from './v1UploadImageResponse';