/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * image.proto
 * OpenAPI spec version: version not set
 */
import type { ProtobufAny } from './protobufAny';

export interface RpcStatus {
  code?: number;
  message?: string;
  details?: ProtobufAny[];
}
